#! python
# Заполненный квадрат
a = int(input('Введите длину сторон квадрата: '))
for i in range(a):
    print('*'*a)

# Пустой квадрат
a = int(input("Введите длину сторон квадрата: "))
print("* " * a)
for i in range(a - 2):
    print("* ", "  " * (a - 3), "* ")
print("* " * a)
